### ISSUE TITLE
make helm-keylime-undeploy should clean jobs & pods

### ISSUE THREAD

**Issue by sarroutbi** [keylime/attestation-operator#27]
I executed Makefile's 'helm-keylime-undeploy' rule, but, after doing so, it seems jobs & pods continue running:

```bash
$ make helm-keylime-undeploy
{ \
helm list --namespace keylime | grep -q hhkl &&\
helm uninstall hhkl --namespace keylime;\
kubectl get persistentvolumeclaim/data-hhkl-mysql-0 --namespace keylime > /dev/null 2>&1 &&\
kubectl delete persistentvolumeclaim/data-hhkl-mysql-0 --namespace keylime;\
kubectl get secret/hhkl-keylime-ca-password --namespace keylime > /dev/null 2>&1 &&\
kubectl delete secret/hhkl-keylime-ca-password --namespace keylime;\
kubectl get secret/hhkl-keylime-mysql-password --namespace keylime > /dev/null 2>&1 &&\
kubectl delete secret/hhkl-keylime-mysql-password --namespace keylime;\
kubectl get secret/hhkl-keylime-certs --namespace keylime > /dev/null 2>&1 &&\
kubectl delete secret/hhkl-keylime-certs --namespace keylime;\
kubectl get secret/hhkl-keylime-tpm-cert-store --namespace keylime > /dev/null 2>&1 &&\
kubectl delete secret/hhkl-keylime-tpm-cert-store --namespace keylime;\
kubectl get secret/hhkl-keylime-tpm-extra-cert-store --namespace keylime > /dev/null 2>&1 &&\
kubectl delete secret/hhkl-keylime-tpm-extra-cert-store --namespace keylime;\
rm -f /home/sarroutb/RedHat/TASKS/KEYLIME/github/sarroutbi/attestation-operator/kt;\
}
release "hhkl" uninstalled
secret "hhkl-keylime-ca-password" deleted
$ kubectl get pods
NAME                         READY   STATUS   RESTARTS   AGE
hhkl-keylime-init-ca-t2ldp   0/1     Error    0          6m13s
hhkl-keylime-init-ca-tpzcq   0/1     Error    0          6m24s
$ kubectl get jobs
NAME                   COMPLETIONS   DURATION   AGE
hhkl-keylime-init-ca   0/1           6m31s      6m31s
```

**Comment by mheese** [comment]
Technically this is not an issue, as this should work perfectly fine on a reinstall, and has been designed to work on a reinstall with both of them present, and must be accounted for during testing. During most "real-life" scenarios you would not want to regenerate the objects that you are now deleting all the time.

**Comment by sarroutbi** [comment]
@mheese : what is your proposal? To keep them running although undeploy is done? Should I create then a new rule for undeploying? I see some cases (such as errored jobs) where it might be useful to clean the job (and associated pods) and relaunch from scratch. But if keeping them was intentionally, we can do this on a new rule different to undeploy

**Comment by mheese** [comment]
@sarroutbi this was more of a statement of providing that information than anything else :) I think the PR was the right thing to merge as it satisfies the more general cleanup use-case, but we should not forget to test that the init jobs should be:
- able to be around on a reinstall, and not break a reinstall
- that if they are around the created secrets truly persist

That said, those init jobs must never error (obviously). And if they error, the whole installation should not work at all. So I am actually curious to understand what happened in your case @sarroutbi . If you are available on slack, let's please have a quick discussion around this.

In general fyi, the init job as well as the secrets that it creates are helm pre-install hooks. They aren't considered being part of the helm installation which is why they don't get removed on a helm uninstall. IMHO they are extremely awkward, but unfortunately necessary at times. Essentially we use it here to prepare/generate secrets which otherwise would need to be provided and created out-of-band. They are a bit cumbersome and difficult to use, and it's likely that I got something wrong in there. As @maugustosilva and I discussed a long time ago a very important feature of the helm charts is to get to a simple default out-of-the-box installation - in which case we want the secrets to be generated. In a real installation I would assume that people will probably want to bring those secrets.

**Comment by sarroutbi** [comment]
Hello @mheese . Just to clarify, I used an OpenShift deployment to test. I guess this is the main issue, as OpenShift has some security constraints, such as running as root (at least, that was the error I was finding). It is related to file:
build/helm/keylime/charts/keylime-init/templates/ca-job.yaml
I needed to check the user running, and download kubectl to /tmp, as /usr/local/bin is not writable in the POD container image, at least, when deployed through OpenShift.
IMHO, this is dangerous:
https://github.com/keylime/attestation-operator/blob/main/build/helm/keylime/charts/keylime-init/templates/ca-job.yaml#L55
It assumes /usr/local/bin is writable, while this is not always true.
Once I reproduce it again, I will open an issue for this particular case.

**Comment by mheese** [comment]
@sarroutbi please create an issue for this :+1: Yes, this should get corrected, I agree. As you can see this was all written "on the go" to get it working. One of two things should be done:

1. add `kubectl` to a docker image, as well as probably the script as well ... this was all done inline for the pod yaml so that I could simply reuse an existing image and not create yet another docker image for just this
2. if we want to keep it like this, then the download should be done probably on an `emptyDir` for which can be ensured that we can download/write to it, as well as execute from it.

Thinking of (2), not sure that will actually work with the default security context constraints on OpenShift either :thinking:

I don't have access to any OpenShift clusters anymore, so I can't really help here, unfortunately. I believe there is probably a whole bunch of the services where the SCC would need to get adjusted, or a different SCC should be used altogether. We probably should write dedicated ones for all the different services if that is necessary.

I remember that in the past, I always had an "openshift=true" parameter in helm charts because there is always something that needs to get adjusted. We probably need to do the same for OpenShift deployments.

**Comment by sarroutbi** [comment]
OK. Thanks for clarifying @mheese . I added #31 to track this issue.
